apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: covid-19-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: covid-19-frontend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50